export * from './asociacin.service';
import { AsociacinService } from './asociacin.service';
export * from './candidatura.service';
import { CandidaturaService } from './candidatura.service';
export * from './cargo.service';
import { CargoService } from './cargo.service';
export * from './consulta.service';
import { ConsultaService } from './consulta.service';
export * from './cuestionario.service';
import { CuestionarioService } from './cuestionario.service';
export * from './genero.service';
import { GeneroService } from './genero.service';
export * from './opcionesDeRespuesta.service';
import { OpcionesDeRespuestaService } from './opcionesDeRespuesta.service';
export * from './pregunta.service';
import { PreguntaService } from './pregunta.service';
export * from './resultados.service';
import { ResultadosService } from './resultados.service';
export * from './simulacion.service';
import { SimulacionService } from './simulacion.service';
export * from './tipoAsociacin.service';
import { TipoAsociacinService } from './tipoAsociacin.service';
export * from './usuario.service';
import { UsuarioService } from './usuario.service';
export * from './visitante.service';
import { VisitanteService } from './visitante.service';
export const APIS = [AsociacinService, CandidaturaService, CargoService, ConsultaService, CuestionarioService, GeneroService, OpcionesDeRespuestaService, PreguntaService, ResultadosService, SimulacionService, TipoAsociacinService, UsuarioService, VisitanteService];
