/**
 * futur-fogueres-api
 * The API for Futur Fogueres project
 *
 * OpenAPI spec version: 1.0.0100
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Candidatura } from '../model/candidatura';
import { CandidaturaResponse } from '../model/candidaturaResponse';
import { CandidaturasResponse } from '../model/candidaturasResponse';
import { InlineResponse200 } from '../model/inlineResponse200';
import { InlineResponse2001 } from '../model/inlineResponse2001';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CandidaturaService {

    protected basePath = 'https://virtserver.swaggerhub.com/FGARCIADEVELOP_1/futurFogueres/1.0.0';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * Borra los datos de la candidatura pasada por parámetro.
     * @param idCandidatura 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteCandidatura(idCandidatura: number, observe?: 'body', reportProgress?: boolean): Observable<InlineResponse2001>;
    public deleteCandidatura(idCandidatura: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InlineResponse2001>>;
    public deleteCandidatura(idCandidatura: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InlineResponse2001>>;
    public deleteCandidatura(idCandidatura: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idCandidatura === null || idCandidatura === undefined) {
            throw new Error('Required parameter idCandidatura was null or undefined when calling deleteCandidatura.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<InlineResponse2001>('delete',`${this.basePath}/candidaturas/${encodeURIComponent(String(idCandidatura))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Devuelve todas los datos de las candidaturas existentes.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllCandidaturas(observe?: 'body', reportProgress?: boolean): Observable<CandidaturasResponse>;
    public getAllCandidaturas(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CandidaturasResponse>>;
    public getAllCandidaturas(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CandidaturasResponse>>;
    public getAllCandidaturas(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<CandidaturasResponse>('get',`${this.basePath}/candidaturas`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Devuelve todos los datos de la candidatura consultada
     * @param idCandidatura 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCandidatura(idCandidatura: number, observe?: 'body', reportProgress?: boolean): Observable<CandidaturaResponse>;
    public getCandidatura(idCandidatura: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CandidaturaResponse>>;
    public getCandidatura(idCandidatura: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CandidaturaResponse>>;
    public getCandidatura(idCandidatura: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idCandidatura === null || idCandidatura === undefined) {
            throw new Error('Required parameter idCandidatura was null or undefined when calling getCandidatura.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<CandidaturaResponse>('get',`${this.basePath}/candidaturas/${encodeURIComponent(String(idCandidatura))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Almacena una nueva candidatura en la base de datos.
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postCandidatura(body?: Candidatura, observe?: 'body', reportProgress?: boolean): Observable<InlineResponse200>;
    public postCandidatura(body?: Candidatura, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InlineResponse200>>;
    public postCandidatura(body?: Candidatura, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InlineResponse200>>;
    public postCandidatura(body?: Candidatura, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<InlineResponse200>('post',`${this.basePath}/candidaturas`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Actualizar una candidatura
     * @param idCandidatura 
     * @param body Item to add
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putCandidatura(idCandidatura: number, body?: Candidatura, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public putCandidatura(idCandidatura: number, body?: Candidatura, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public putCandidatura(idCandidatura: number, body?: Candidatura, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public putCandidatura(idCandidatura: number, body?: Candidatura, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idCandidatura === null || idCandidatura === undefined) {
            throw new Error('Required parameter idCandidatura was null or undefined when calling putCandidatura.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/candidaturas/${encodeURIComponent(String(idCandidatura))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
